version: 2
updates:
  # Node.js dependencies for tweet-service
  - package-ecosystem: "npm"
    directory: "/tweet-service"
    schedule:
      interval: "daily"

  # Dockerfile for tweet-service
  - package-ecosystem: "docker"
    directory: "/tweet-service"
    schedule:
      interval: "daily"

  # Node.js dependencies for timeline-service
  - package-ecosystem: "npm"
    directory: "/timeline-service"
    schedule:
      interval: "daily"

  # Dockerfile for timeline-service
  - package-ecosystem: "docker"
    directory: "/timeline-service"
    schedule:
      interval: "daily"
