version: '3.8'

services:
  tweet-service:
    build: ./tweet-service
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=amqp://rabbitmq
      - TWEET_QUEUE=new_tweets
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - rabbitmq

  timeline-service:
    build: ./timeline-service
    ports:
      - "4000:4000"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
      - TWEET_QUEUE=new_tweets
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

networks:
  backend:
