apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tweet-service
  template:
    metadata:
      labels:
        app: tweet-service
    spec:
      priorityClassName: high-priority
      containers:
        - name: tweet-service
          image: jaimydocker/jaimy_docker:tweet-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: tweet-db-secret
          env:
            - name: RABBITMQ_URL
              value: amqp://rabbitmq
            - name: TWEET_QUEUE
              value: new_tweets
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth0-secret
                  key: AUTH0_DOMAIN
            - name: AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: auth0-secret
                  key: AUTH0_AUDIENCE
            - name: SENDMAIL_URL
              valueFrom:
                secretKeyRef:
                  name: auth0-secret
                  key: SENDMAIL_URL
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 3000
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
