name: Node.js CI - Timeline Service

on:
  push:
    paths:
      - 'timeline-service/**'
  pull_request:
    paths:
      - 'timeline-service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: timeline-service

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./timeline-service
        file: ./timeline-service/Dockerfile
        push: true
        tags: |
          jaimydocker/jaimy_docker:timeline-latest
          jaimydocker/jaimy_docker:timeline-${{ github.sha }}

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
