name: Node.js CI - User Service

on:
  push:
    paths:
      - 'user-service/**'
  pull_request:
    paths:
      - 'user-service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: user-service

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./user-service
        file: ./user-service/Dockerfile
        push: true
        tags: |
          jaimydocker/jaimy_docker:user-service-latest
          jaimydocker/jaimy_docker:user-service-${{ github.sha }}

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install
